<a href="https://colab.research.google.com/github/Arpitsinghvampire/PyTorch_codes/blob/main/PyTorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__


'2.6.0+cu124'

In [ ]:
#now lets create a torch tensor
scalar = torch.tensor(7)

print(scalar)

#now if we want to extract the number from tensor
print(scalar.item()) # turn the torch.Tensor to Python integer



tensor(7)
7


In [ ]:
#vector
vector = torch.tensor([7,7]) # the tensor is 7,7

vector
#lets check the dimension of the vector
print(vector.ndim)
print(vector.shape)


1
torch.Size([2])


In [ ]:
#lets now create a matrix
matrix = torch.tensor([[7,8],[9,10]])

matrix

print(matrix.ndim)

2


In [ ]:
Tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

Tensor

print(Tensor.ndim)
print(Tensor.shape)


3
torch.Size([1, 3, 3])


In [ ]:
#lets create the random set of tensors
random_tensor = torch.rand(size=(3,4,3))

random_tensor
print(random_tensor.shape)
print(random_tensor.size())
print(random_tensor.ndim)


torch.Size([3, 4, 3])
torch.Size([3, 4, 3])
3


In [ ]:
#now lets create the set of zeros and ones
zeros = torch.zeros(size =(3,4))
ones = torch.ones(size = (3,4))

print(zeros.shape)
print(zeros.ndim)
print(zeros.size())
print(zeros.dtype)

print(ones.shape)
print(ones.ndim)
print(ones.size())
print(ones.dtype)

torch.Size([3, 4])
2
torch.Size([3, 4])
torch.float32
torch.Size([3, 4])
2
torch.Size([3, 4])
torch.float32


In [ ]:
zero_to_ten_tensor = torch.arange(0,10,1)#start step , stop set and step set

zero_to_ten_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#sometimes we may want one tensor to be a certain type with same shape as another tensor
ten_zeros = torch.zeros_like(input = zero_to_ten_tensor)

ten_zeros

ten_ones = torch.ones_like(input = zero_to_ten_tensor)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
float_32_tensor = torch.tensor([3,6,9],dtype = torch.float32,device = None,requires_grad = False)

print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [ ]:
float_16_tensor = torch.tensor([3,6,9],dtype = torch.float16,device = None,requires_grad = False)
print(float_16_tensor+float_32_tensor)#this should give an error

vector = float_16_tensor+float_32_tensor

print(vector.dtype)
print(vector)
print(vector.device)

tensor([ 6., 12., 18.])
torch.float32
tensor([ 6., 12., 18.])
cpu


In [ ]:
#now lets start by doing the operations on the tensors , the normal addition , subtraction , multiplicationa and division
tensor = torch.rand(size = (3,1))
print(tensor)
print(tensor.shape)
print(tensor.size())
print(tensor.ndim)

print(tensor+10)
print(tensor*10)
print(tensor-10)
print(tensor/10)


tensor([[0.9446],
        [0.8891],
        [0.8970]])
torch.Size([3, 1])
torch.Size([3, 1])
2
tensor([[10.9446],
        [10.8891],
        [10.8969]])
tensor([[9.4463],
        [8.8906],
        [8.9695]])
tensor([[-9.0554],
        [-9.1109],
        [-9.1031]])
tensor([[0.0945],
        [0.0889],
        [0.0897]])


In [ ]:
#in order to do the above operations we can also do the following
Torch_tensor = torch.tensor([1,2,3], dtype = torch.float32)
print(torch.mul(Torch_tensor,10)) #multipliesthe torch tensor by 10 to each element
print(torch.add(Torch_tensor,10))#adds 10 to each element in tensor
print(torch.sub(Torch_tensor,10))#subtracts 10 from each element)
print(torch.div(Torch_tensor,10))#divides each element of the torch tensor by 10


tensor([10., 20., 30.])
tensor([11., 12., 13.])
tensor([-9., -8., -7.])
tensor([0.1000, 0.2000, 0.3000])


In [ ]:
print(Torch_tensor*Torch_tensor)
print(torch.matmul(Torch_tensor,Torch_tensor.T))

#there is a difference between the element wise multiplication and the matrix multiplication

#in element wise multiplication the matrices are multiplied element wise , in matrix multiplication we have the standard multiplication



tensor([1., 4., 9.])
tensor(14.)


In [ ]:
#element wise multiplication
print(Torch_tensor*Torch_tensor)

#matrix multiplication
print(torch.matmul(Torch_tensor,Torch_tensor.T))#since the dimensions must match for a valid matrix multiplication

print(Torch_tensor@Torch_tensor.T) #take the transpose of the second matrix

tensor([1., 4., 9.])
tensor(14.)
tensor(14.)


In [ ]:
#in this exercise we start with the oprations for min. and max and other stuff
#lets start with an array

x = torch.arange(0,100) #by default the step size is 1

print(x.min().item())
print(x.max().item())
print(x.sum().item())
print(x.type(torch.float32).mean().item())


0
99
4950
49.5


In [ ]:
#now we can do the same with the torch function
print(torch.min(x).item())
print(torch.max(x).item())
print(torch.sum(x).item())
print(torch.mean(x.type(torch.float32)).item())

0
99
4950
49.5


In [ ]:
print(x)

print(f"THE POSITION WHERE THE MINIMU. OCCURS IS {torch.argmin(x)}")
print(f"THE POSITION WHERE THE MAXIMUM OCCURS IS {torch.argmax(x)}")



tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])
THE POSITION WHERE THE MINIMU. OCCURS IS 0
THE POSITION WHERE THE MAXIMUM OCCURS IS 99


In [ ]:
import torch

x=torch.arange(1,8)
print(x)
print(x.shape)

x_reshaped = x.reshape(1,7)
print(x_reshaped)
print(x_reshaped.shape)

z = x.view(7,1)
print(z)
print(z.shape)

tensor([1, 2, 3, 4, 5, 6, 7])
torch.Size([7])
tensor([[1, 2, 3, 4, 5, 6, 7]])
torch.Size([1, 7])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]])
torch.Size([7, 1])


In [ ]:
#now lets stack the value
x_stacked = torch.stack([x,x,x,x,x],dim = 0)
x_stacked_horizontally = torch.stack([x,x,x,x,x],dim =1)

print(x_stacked)
print(x_stacked_horizontally)

tensor([[1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7],
        [1, 2, 3, 4, 5, 6, 7]])
tensor([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7]])


In [ ]:
print(z.shape)
z= z.squeeze()
print(z.shape)

z=z.unsqueeze(dim = 0) #add the 1 dimension at the start
print(z.shape)


torch.Size([7])
torch.Size([7])
torch.Size([1, 7])


In [ ]:
#now we try to interchange the tensor and the numpy
import  torch
import numpy as np

z = np.arange(1,8)
#now we try to typecast them into tensors
z=torch.from_numpy(z)
z_numpy = z.numpy()

In [ ]:
import torch
import random

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)


random_tensor_A = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

random_tensor_A == random_tensor_B


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
#NOW HERE WE NEED TO GET THE PYTORCH TO RUN ON. THE GPU
import torch

#ow lets see whether the cuda is available or not
torch.cuda.is_available()
torch.cuda.device_count()

0