<a href="https://colab.research.google.com/github/Arpitsinghvampire/PyTorch_codes/blob/main/TENSORS_INTRO_PYTORCH_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#TENSORS ARE SIMILAR TO THE NUMPY ARRAY , BUT TENSORS CAN RUN ON THE GPU  , AND TENSORS ARE OPTIMIZED FOR AUTOMATIC DIFFERENTIATION
#INITIALIZING A TENSOR
import torch
import numpy as np

data = [[1,2] , [3,4]]
x_data = torch.tensor(data) #this converts the above list into the torch tensor object

#torch can also be converted from the numpy array
np_array = np.array(data)
np_array_tensor = torch.tensor(np_array)

print(np_array_tensor)

tensor([[1, 2],
        [3, 4]])


TORCH.RAND_LIKE , TORCH.ONES_LIKE , TORCH.ZEROS_LIKE ,  get certain values following a particular structure

In [7]:
#tensor can also be converted to have a value but the structure is same as one of the tensors
x_ones = torch.ones_like(x_data) #argument must be a tensor

#x_ones1 = torch.ones_like(np_array) #this part will give an error , the argument must contain only a tensor in the parameter
#print(x_ones1)
print(x_ones)

#similarly we can create a random tensor having the same structure as one of the tensors
x_rand = torch.rand_like(x_data , dtype = torch.float) #this will create a random torch tensor having the same structure as  the parameter tensor , but each having its own value
print(x_rand)


tensor([[1, 1],
        [1, 1]])
tensor([[0.7368, 0.2479],
        [0.4809, 0.0228]])


torch.rand , torch.ones, torch.zeros take in a shape as a parameter and then return the matrix of the required shape

In [11]:
#now lets look at other ways of getting a tensor
rand_tensor = torch.rand((2,3))
print(rand_tensor)

#similarly we can create other matrices liek the 0 matrices and the 1 matrices
ones_tensor = torch.ones((2,3))
print(ones_tensor)
zero_tensor = torch.zeros((2,3))
print(zero_tensor)

#in short here we use torch.rand to get a random number of the shape defined earlier
#we also use torch.ines and torch.zeros

tensor([[0.7601, 0.9914, 0.8858],
        [0.4434, 0.2769, 0.2436]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


ATTRIBUTES OF THE TENSOR

In [16]:
rand_tensor = torch.rand((2,3))
print(rand_tensor)

print(rand_tensor.dtype)
print(rand_tensor.shape)
print(rand_tensor.device)

tensor([[0.9335, 0.6532, 0.5340],
        [0.2081, 0.7653, 0.5539]])
torch.float32
torch.Size([2, 3])
cpu


OPERATIONS ON TENSORS

In [17]:
#NOW LETS SEE IF THE ACCELERATOR IS REALLY AVAILABLE OR NOT
if torch.cuda.is_available():
  #then move everything to the accelerator
  rand_tensor = rand_tensor.to(torch.accelerator.current_accelerator())

In [20]:
rand_tensor = torch.rand(4,4)

print(f"the first row is {rand_tensor[0]}")
print(f"the first column is {rand_tensor[:,0]}")
print(f"the last column is {rand_tensor[...,-1]}")

the first row is tensor([0.7907, 0.5838, 0.6190, 0.0513])
the first column is tensor([0.7907, 0.6021, 0.8964, 0.1294])
the last column is tensor([0.0513, 0.8881, 0.6618, 0.9608])


CONCATENATE THE TENSORS


In [19]:
T1 = torch.cat([rand_tensor , rand_tensor , rand_tensor] , dim =1) #this concatenates on the column  adds the column
print(T1)

T2 = torch.cat([rand_tensor , rand_tensor , rand_tensor] , dim = 0 ) #this concatenates on the row
print(T2)

tensor([[0.9335, 0.6532, 0.5340, 0.9335, 0.6532, 0.5340, 0.9335, 0.6532, 0.5340],
        [0.2081, 0.7653, 0.5539, 0.2081, 0.7653, 0.5539, 0.2081, 0.7653, 0.5539]])
tensor([[0.9335, 0.6532, 0.5340],
        [0.2081, 0.7653, 0.5539],
        [0.9335, 0.6532, 0.5340],
        [0.2081, 0.7653, 0.5539],
        [0.9335, 0.6532, 0.5340],
        [0.2081, 0.7653, 0.5539]])


In [21]:
#now we can matrix
y1 = rand_tensor @ rand_tensor.T
y2 = torch.matmul(rand_tensor , rand_tensor.T)

y3 = torch.rand_like(y1) #gives a random matrix of the  shape y1 .
torch.mul(rand_tensor , rand_tensor.T, out = y3)


#this computes the element wise product
z1= rand_tensor*rand_tensor
z2 = rand_tensor.mul(rand_tensor)
z3 = torch.rand_like(rand_tensor)
torch.mul(rand_tensor , rand_tensor , out = z3)


tensor([[0.6252, 0.3409, 0.3832, 0.0026],
        [0.3625, 0.1715, 0.0087, 0.7887],
        [0.8034, 0.7333, 0.1721, 0.4380],
        [0.0167, 0.4617, 0.1980, 0.9231]])

Single Element  tensors  .If you have a one element tensor  , by aggregating the values of teh tensor into one value , you can convert into a python numerical value using  item()


In [22]:
aggregate = rand_tensor.sum()
aggregate_item = aggregate.item()
print(aggregate_item , type(aggregate_item))

9.086289405822754 <class 'float'>


Numpy  array to  Tensor

In [25]:
n = np.ones(5)
t = torch.from_numpy(n) #converts  numpy array to torch tensor
#this is  earlier version
print(n)
print(t)

#this is the updated version
n = n+1
print(n)
print(t)



[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
